### ISSUE TITLE
 not a valid Cucumber report! String length (20051119) exceeds the maximum length (20000000)

### ISSUE THREAD

**Issue by waynemd** [jenkinsci/cucumber-reports-plugin#449]
### Jenkins and plugins versions report

<details>
  <summary>json is not a valid Cucumber report! String length (20051119) exceeds the maximum length (20000000) </summary>

  
  ```text
net.masterthought.cucumber.ValidationException: File '.../cucumber-html-reports/.cache/parallel/_.json' is not a valid Cucumber report! String length (20051119) exceeds the maximum length (20000000) (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][0]->net.masterthought.cucumber.json.Element["after"]->java.lang.Object[][0]->net.masterthought.cucumber.json.Hook["embeddings"]->java.lang.Object[][0])
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:102)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:69)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:97)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:563)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:767)
	at hudson.model.Build$BuildExecution.post2(Build.java:179)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:711)
	at hudson.model.Run.execute(Run.java:1925)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Caused by: com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (20051119) exceeds the maximum length (20000000)
	at com.fasterxml.jackson.core.StreamReadConstraints.validateStringLength(StreamReadConstraints.java:324)
	at com.fasterxml.jackson.core.util.ReadConstrainedTextBuffer.validateStringLength(ReadConstrainedTextBuffer.java:27)
	at com.fasterxml.jackson.core.util.TextBuffer.finishCurrentSegment(TextBuffer.java:939)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2240)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2206)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:323)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:572)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:100)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3084)
	at net.masterthought.cucumber.json.deserializers.CucumberJsonDeserializer.deserialize(CucumberJsonDeserializer.java:25)
	at net.masterthought.cucumber.json.deserializers.EmbeddingDeserializer.deserialize(EmbeddingDeserializer.java:22)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3785)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:90)
	... 15 more
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

controller on linux and agent on mac 

### Reproduction steps

The problem is showing on the latest version of cucumber report plugin 5.8.0(https://plugins.jenkins.io/cucumber-reports)
rolling back to last version 5.7.6 looks ok. 

Jenkins Version 2.414.2

### Expected Results

should create a valid cucumber report

### Actual Results

fails

**Comment by damianszczepanik** [comment]
Should be fixed with [1f42c4505112d42e78f523749e7672e705a19b04 ](https://github.com/damianszczepanik/cucumber-reporting/commit/1f42c4505112d42e78f523749e7672e705a19b04) so check recent version of the plugin which collects 2.15 https://github.com/FasterXML/jackson-core/pull/1018

**Comment by felipecrs** [comment]
@damianszczepanik I am still facing this issue with Cucumber Reports 5.8.0 and Jackson 2.15.3-366.vfe8d1fa_f8c87:

```
net.masterthought.cucumber.ValidationException: File '/var/jenkins_home/jobs/build/builds/2522/cucumber-html-reports/.cache/cucumber-html-reports/Some.features.getFeature.json' is not a valid Cucumber report! String length (20054016) exceeds the maximum length (20000000) (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][11]->net.masterthought.cucumber.json.Element["steps"]->java.lang.Object[][17]->net.masterthought.cucumber.json.Step["doc_string"]->net.masterthought.cucumber.json.DocString["value"])
at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:102)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:69)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:97)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:563)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:434)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (20054016) exceeds the maximum length (20000000)
	at com.fasterxml.jackson.core.StreamReadConstraints.validateStringLength(StreamReadConstraints.java:324)
	at com.fasterxml.jackson.core.util.ReadConstrainedTextBuffer.validateStringLength(ReadConstrainedTextBuffer.java:27)
	at com.fasterxml.jackson.core.util.TextBuffer.finishCurrentSegment(TextBuffer.java:939)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2240)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2206)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:323)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:42)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:216)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3785)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:90)
	... 13 more
```

**Comment by damianszczepanik** [comment]
Suggest to pass this problem to fasterxml

**Comment by felipecrs** [comment]
Hm... But I read in some places that this size/length is already made configurable by Jackson. I am wondering if it isn't a matter of just passing in a bigger size from the cucumber reports plugin when calling Jackson.

**Comment by felipecrs** [comment]
This: https://github.com/FasterXML/jackson-core/issues/1014#issuecomment-1624350361

**Comment by damianszczepanik** [comment]
BTW, what makes your report so big, what element?

**Comment by waynemd** [comment]
usually, it is the big video record attachment to the report

**Comment by felipecrs** [comment]
> Fix for this is on the way [damianszczepanik/cucumber-reporting#1265](https://github.com/damianszczepanik/cucumber-reporting/pull/1265) - is anyone ready to test it ?

That's awesome, @damianszczepanik. If you can generate an hpi, I can test it in my Jenkins.

**Comment by damianszczepanik** [comment]
> > Fix for this is on the way [damianszczepanik/cucumber-reporting#1265](https://github.com/damianszczepanik/cucumber-reporting/pull/1265) - is anyone ready to test it ?
> 
> That's awesome, [@damianszczepanik](https://github.com/damianszczepanik). If you can generate an hpi, I can help you by testing it in my Jenkins.

hpi file is built - get it from https://ci.jenkins.io/job/Plugins/job/cucumber-reports-plugin/job/PR-529/

**Comment by damianszczepanik** [comment]
> [@damianszczepanik](https://github.com/damianszczepanik) I suppose I need to increase the `maxStreamStringLength` by myself, right?
> 
> Do you mind sharing how? From [#529](https://github.com/jenkinsci/cucumber-reports-plugin/pull/529) I don't see this new configuration being exposed to the `cucumber` step.

#529 is fixed and new 5.10.0 hpi file is ready to download https://ci.jenkins.io/job/Plugins/job/cucumber-reports-plugin/view/change-requests/job/PR-529/2/
I recommend first to check with new job and do not modify production. You will find new option at the end of the advanced section for the plugin - read documentation and check what value fixes the problem

**Comment by damianszczepanik** [comment]
> I am getting the same error on my instance too with 5.10.0

What is the JSON  file size you have and what was the value of the max length which you have used in plugin confirmation?

**Comment by felipecrs** [comment]
The value I used in the configuration was 25000000, as mentioned in my comment.

I'll try getting the JSON file.

**Comment by waynemd** [comment]
> > I am getting the same error on my instance too with 5.10.0
> 
> What is the JSON file size you have and what was the value of the max length which you have used in plugin confirmation?
I see this in log:  
`Caused by: com.fasterxml.jackson.core.exc.StreamConstraintsException: String value length (20054016) exceeds the maximum allowed (20000000, from `StreamReadConstraints.getMaxStringLength()`)
....
Trying to generate report from following files. Make sure they are valid cucumber report files:
.../builds/3219/cucumber-html-reports/.cache/parallel/_.json
.../builds/3219/cucumber-html-reports/.cache/parallel/_rerun.json`

I dont see the json files in the .cache directory anymore after the run though.  maybe it has been deleted.  I also set the 25000000 in the advanced settings configuration

**Comment by felipecrs** [comment]
@damianszczepanik I got it. It's a 120MB JSON file whose longest string has 32746521 characters.

However, I cannot share it as it contains company-sensitive details. :(

**Comment by felipecrs** [comment]
Awesome news, @damianszczepanik. I'm eager to try it. :)

**Comment by damianszczepanik** [comment]
> Awesome news, [@damianszczepanik](https://github.com/damianszczepanik). I'm eager to try it. :)

new hpi file should be soon available https://ci.jenkins.io/job/Plugins/job/cucumber-reports-plugin/view/change-requests/job/PR-529/ - waiting for the Jenkins to start the build

**Comment by damianszczepanik** [comment]
Published https://ci.jenkins.io/job/Plugins/job/cucumber-reports-plugin/view/change-requests/job/PR-529/3/artifact/

**Comment by felipecrs** [comment]
It worked for me too, but at the end of the day I had to increase the limit to 100000000! Thank you so much, @damianszczepanik!

**Comment by damianszczepanik** [comment]
Fix has been just released
